services:
  llm_service:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./init.sh:/init.sh
    deploy:
      resources:
        limits:
          memory: 4G
    entrypoint: ["/bin/bash", "/init.sh"]

  vector_db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  rag_api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - llm_service
      - vector_db
    environment:
      - OLLAMA_HOST=http://llm_service:11434
      - QDRANT_HOST=http://vector_db:6333

volumes:
  ollama_models:
  qdrant_data: